<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets/pet.ico</ApplicationIcon>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
